version: '3.1'

services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  migrate:
    image: migrate/migrate
    depends_on:
      - database
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:docker@database:5432/postgres?sslmode=disable",
        "up"
      ]

volumes:
  db:
    driver: local
  migrations:


